services:
  webclient:
    build:
      context: ./peerpedia-webclient
      dockerfile: Dockerfile
    container_name: webclient

  app-server-1:
    build:
      context: ./peerpedia-server
      dockerfile: Dockerfile
    container_name: app-server-1
    env_file:
      - ./app-server.env
    depends_on:
      - cache

  app-server-2:
    build:
      context: ./peerpedia-server
      dockerfile: Dockerfile
    container_name: app-server-2
    env_file:
      - ./app-server.env
    depends_on:
      - cache

  load-balancer:
    build:
      context: ./peerpedia-load-balancer
      dockerfile: Dockerfile
    container_name: load-balancer
    ports:
      - "80:80"
    depends_on:
      - app-server-1
      - app-server-2
      - webclient

  cache:
    build:
      context: ./peerpedia-cache
      dockerfile: Dockerfile
    container_name: cache
    ports:
      - "6379:6379"
