services:
  webclient:
    build:
      context: ./peerpedia-webclient
      dockerfile: Dockerfile
    container_name: webclient
    ports:
      - "5173:5173"
    env_file:
      - ./.env/webclient.env

  app-server-1:
    build:
      context: ./peerpedia-server
      dockerfile: Dockerfile
    container_name: app-server-1
    ports:
      - "8081:8080"
    env_file:
      - ./.env/app-server.env
    depends_on:
      - cache

  app-server-2:
    build:
      context: ./peerpedia-server
      dockerfile: Dockerfile
    container_name: app-server-2
    ports:
      - "8082:8080"
    env_file:
      - ./.env/app-server.env
    depends_on:
      - cache

  load-balancer:
    image: nginx:latest
    container_name: load-balancer
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app-server-1
      - app-server-2
      - webclient

  cache:
    image: redis:6-alpine
    container_name: cache
    ports:
      - "6379:6379"
