services:
  webclient:
    build:
      context: ./peerpedia-webclient
      dockerfile: Dockerfile
    container_name: webclient
    volumes:
      - ./config/webclient/nginx.conf:/etc/nginx/nginx.conf

  app-server-1:
    build:
      context: ./peerpedia-server
      dockerfile: Dockerfile
    container_name: app-server-1
    env_file:
      - ./config/app-server/.env
    depends_on:
      - cache

  app-server-2:
    build:
      context: ./peerpedia-server
      dockerfile: Dockerfile
    container_name: app-server-2
    env_file:
      - ./config/app-server/.env
    depends_on:
      - cache

  load-balancer:
    image: nginx:latest
    container_name: load-balancer
    volumes:
      - ./config/load-balancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app-server-1
      - app-server-2
      - webclient

  cache:
    image: redis:6-alpine
    container_name: cache
    ports:
      - "6379:6379"
