services:
  - type: web
    name: peerpedia
    runtime: docker
    dockerContext: ./peerpedia-load-balancer
    dockerfilePath: ./peerpedia-load-balancer/Dockerfile
    plan: free
    autoDeployTrigger: off
  
  - type: web
    name: webclient
    runtime: docker
    dockerContext: ./peerpedia-webclient
    dockerfilePath: ./peerpedia-webclient/Dockerfile
    plan: free
    autoDeployTrigger: off
  
  - type: web
    name: app-server-1
    runtime: docker
    dockerContext: ./peerpedia-server
    dockerfilePath: ./peerpedia-server/Dockerfile
    plan: free
    autoDeployTrigger: off
    envVars:
      - fromGroup: app-server-env

  - type: web
    name: app-server-2
    runtime: docker
    dockerContext: ./peerpedia-server
    dockerfilePath: ./peerpedia-server/Dockerfile
    plan: free
    autoDeployTrigger: off
    envVars:
      - fromGroup: app-server-env

  - type: web
    name: cache
    runtime: docker
    dockerContext: ./peerpedia-cache
    dockerfilePath: ./peerpedia-cache/Dockerfile
    plan: free
    autoDeployTrigger: off

  - type: keyvalue
    name: cache
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

envVarGroups:
  - name: app-server-env
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: REDIS_HOST
        fromService:
          name: cache
          type: keyvalue
          property: host
      - key: REDIS_PORT
        fromService:
          name: cache
          type: keyvalue
          property: port
      - key: REDIS_PASSWORD
        fromService:
          name: cache
          type: keyvalue
          property: password
      - key: CACHE_TYPE
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENABLE_WEBCLIENT_CORS
        sync: false
      - key: WEBCLIENT_CORS_DOMAIN
        sync: false
      - key: USER_INCLUDE_COUNT
        sync: false