services:
  - type: web
    name: load-balancer
    runtime: docker
    dockerfilePath: ./peerpedia-load-balancer/Dockerfile
    plan: free
    autoDeploy: false
  
  - type: web
    name: webclient
    runtime: docker
    dockerfilePath: ./peerpedia-webclient/Dockerfile
    plan: free
    autoDeploy: false
  
  - type: web
    name: app-server-1
    runtime: docker
    dockerfilePath: ./peerpedia-server/Dockerfile
    plan: free
    autoDeploy: false
    envVars:
      - key: DB_URL
      - key: DB_USERNAME
      - key: DB_PASSWORD
      - key: REDIS_HOST
      - key: REDIS_PORT
      - key: REDIS_PASSWORD
      - key: CACHE_TYPE
      - key: ADMIN_PASSWORD
      - key: JWT_SECRET
      - key: ENABLE_WEBCLIENT_CORS
      - key: WEBCLIENT_CORS_DOMAIN
      - key: USER_INCLUDE_COUNT

  - type: web
    name: app-server-2
    runtime: docker
    dockerfilePath: ./peerpedia-server/Dockerfile
    plan: free
    autoDeploy: false
    envVars:
      - key: DB_URL
      - key: DB_USERNAME
      - key: DB_PASSWORD
      - key: REDIS_HOST
      - key: REDIS_PORT
      - key: REDIS_PASSWORD
      - key: CACHE_TYPE
      - key: ADMIN_PASSWORD
      - key: JWT_SECRET
      - key: ENABLE_WEBCLIENT_CORS
      - key: WEBCLIENT_CORS_DOMAIN
      - key: USER_INCLUDE_COUNT

  - type: web
    name: cache
    runtime: docker
    dockerfilePath: ./peerpedia-cache/Dockerfile
    plan: free
    autoDeploy: false