services:
  - type: web
    name: peerpedia
    region: singapore
    runtime: docker
    dockerContext: ./peerpedia-webclient
    dockerfilePath: ./peerpedia-webclient/Dockerfile
    plan: free
    autoDeployTrigger: off
  
  - type: web
    name: peerpedia-app-server
    region: singapore
    runtime: docker
    dockerContext: ./peerpedia-server
    dockerfilePath: ./peerpedia-server/Dockerfile
    plan: free
    autoDeployTrigger: off
    envVars:
      - fromGroup: peerpedia-app-server-env

envVarGroups:
  - name: peerpedia-app-server-env
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: CACHE_TYPE
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENABLE_WEBCLIENT_CORS
        sync: false
      - key: WEBCLIENT_CORS_DOMAIN
        sync: false
      - key: USER_INCLUDE_COUNT
        sync: false