spring:
  application:
    name: peerpedia
  datasource:
    url: jdbc:postgresql://${DB_URL}/peerpedia
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 600000 # 10 mins = 10 * 60 * 1000
      connection-timeout: 30000 # 30 sec = 30 * 1000
  jpa:
    hibernate:
      ddl-auto: update # other values: create, create-drop, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  file:
    name: ./logs/server.log
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.web.filter: TRACE
#    org.springframework.web.servlet.DispatcherServlet: DEBUG
#    org.springframework.web.cors: DEBUG

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-in-ms: 86400000 # 1 day = 24 * 60 * 60 * 1000
  frontend-domain: ${FRONTEND_DOMAIN}
  admin:
    password: ${ADMIN_PASSWORD}